### ISSUE TITLE
Paging performance

### ISSUE THREAD

**Issue by digitalseas** [gentics/mesh#1057]
Hi,

We encounter an issue for paging. On a 300,000 nodes test site. The paging seems to become slower and slower when the "page" variable increases. See below performance test.

Tested on http://localhost/test-category?page=1000

Page=1: - 127.0.0.1 - POST /api/v1/demo/graphql HTTP/1.1 200 996 - 24 ms
Page=100: - 127.0.0.1 - POST /api/v1/demo/graphql HTTP/1.1 200 86090 - 214 ms
Page=200: - 127.0.0.1 - POST /api/v1/demo/graphql HTTP/1.1 200 86075 - 213 ms
Page=1000: - 127.0.0.1 - POST /api/v1/demo/graphql HTTP/1.1 200 83612 - 860 ms
Page=2000: - 127.0.0.1 - POST /api/v1/demo/graphql HTTP/1.1 200 82387 - 2152 ms
Page=3000: - 127.0.0.1 - POST /api/v1/demo/graphql HTTP/1.1 200 90572 - 2468 ms
Page=4000: - 127.0.0.1 - POST /api/v1/demo/graphql HTTP/1.1 200 86315 - 3738 ms
Page=5000:- 127.0.0.1 - POST /api/v1/demo/graphql HTTP/1.1 200 83151 - 4898 ms
Page=6000:- 127.0.0.1 - POST /api/v1/demo/graphql HTTP/1.1 200 86156 - 6044 ms
Page=7000:- 127.0.0.1 - POST /api/v1/demo/graphql HTTP/1.1 200 82698 - 7024 ms
Page=8000:- 127.0.0.1 - POST /api/v1/demo/graphql HTTP/1.1 200 82895 - 8526 ms
Page=9000:- 127.0.0.1 - POST /api/v1/demo/graphql HTTP/1.1 200 90852 - 9994 ms
Page=9500: - 127.0.0.1 - POST /api/v1/demo/graphql HTTP/1.1 200 87900 - 11577 ms

Eventually, we will see an OKHttp connection timeout error. 
In the GraphQL, we already disabled "totalCount" and "pageCount":
```
 # Total amount of found elements
 #totalCount
 # Total amount of found pages. Each page has a size of 2
 # pageCount 
```

Is there any other way we can improve paging performance?

Thanks in advance for the help!

**Comment by Jotschi** [comment]
@digitalseas This is a known performance topic. We have a section on how to best deal with this:

https://getmesh.io/docs/performance/#_paging

If possible avoid using the pageCount/totalCount field. It is relatively costly to calculate (permissions need to be checked for all elements in order to compute the correct pageCount/totalCount. You could also look at using Elasticsearch queries to further narrow your result. It is also possible to execute such queries within GraphQL.

We are aware of this performance problem and at the moment we can't do much about it. We have however some ideas in the long term to deal with those.

**Comment by Jotschi** [comment]
Let me know whether you have any other question.
