### ISSUE TITLE
Improve search-reindexing and creation of the new search-index during schema migration

### ISSUE THREAD

**Issue by sebastianvogel** [gentics/mesh#138]
## Problem
The existing data is not available in the search-index during reindex and schema-migration. Implementations of clients that are dependent on the elastic-search (including Mesh-UI) will not be working properly during those operations because they will have no data available at all. Indexing can be slow when many objects are stored in Mesh this is situation has to be improved to at least get the existing data from the search index while the reindex operation is performed in the background.

**Comment by Jotschi** [comment]
## Possible Solution

### A - Isolate unfinished migrations

The migrated data will only be accessible once the migration finishes. Other requests will access the old index. This index will be removed once the queued migration finishes.

### B - Mix indices of finished and unfinished migrations/schema versions

Could lead to inconsistent search results. A not yet migrated node could be found but was now already migrated and thus should actually not be included in the search result.

### C - Differential migration sync

The migrated nodes will be removed from the old index and added to the new index. The search would utilize both indices.

The old index will be removed once all nodes have been migrated.

**Comment by Jotschi** [comment]
## Migration Lock
All solutions require a migration lock/release assignment lock. This would prevent additional HAS_VERSION edges from being created in between release and schema version. We only allow this once the latest version migration is "completed".

## Migration without lock

Alternatively we could allow further node migrations and thus deal with migration failures by rolling back to a specific schema version. This would potentially also require the index to be recreated. The index must be updated and the documents must be stored.

This variation would work better with solution A/B since rollback is faster.

**Comment by Jotschi** [comment]
Related to #143

**Comment by Jotschi** [comment]
Option C implement in 0.10.4
