### ISSUE TITLE
Do not deprecate "expandAll" on /{project}/nodes/{nodeUuid} endpoint

### ISSUE THREAD

**Issue by sebastianvogel** [gentics/mesh#180]
## Gentics Mesh Version, operating system, or hardware.
- v0.10.4

## Problem

The "expandAll" query parameter is deprecated on all rest endpoints in favour of qraphql implementations. While this may be a good idea when fetching multiple nodes, deprecating this feature when fetching a single node via /{project}/nodes/{nodeUuid} makes frontend implementations unnecessary complicated. (especially if we need to support displaying and editing of many different schemas in a generic way)

It should be possible to still use the expandAll parameter (or something similiar) when fetching  a single node via /{project}/nodes/{nodeUuid} - doing this should fetch all directly referenced nodes of the requested node.

**Comment by Jotschi** [comment]
The `expandAll` will be deprecated. This is a decision we made a while ago. Frontend implementations which make use of deeply nested data should use graphql instead.

**Comment by sebastianvogel** [comment]
Please reconsider supporting {{expandAll}} when fetching a single node because generic solutions for projects with many different schemas or projects using MeshCR will be very complicated to implement using graphql.

**Comment by Jotschi** [comment]
* expandAll breaks etag handling. Requests which use expandAll will not get a correct etag
* It causes unnecessary overhead when generating responses
* The expandAll code is complex and should be removed since we have a viable alternative
* New users of Gentics Mesh should not use expandAll since graphql presents a way more efficient solution

Maybe we can find a way to make graphql easier to be used in projects which use a lot of schemas. You can create an issue on that topic if you wish.
