### ISSUE TITLE
Does mesh use Tinkerpop?

### ISSUE THREAD

**Issue by magick93** [gentics/mesh#199]
Hello

Mesh looks very interesting. My only concern, that is holding me back from spending time on it, is OrientDb. 

Is this the only graph db that works with Mesh? 

Do you use http://tinkerpop.apache.org/ ?

Thanks

**Comment by aschauerhuber** [comment]
yes, since we are using Apache TinkerPop, it's definitely possible to use other Graph DBs. We are playing around with Stardog and Neo4J at the moment, but these are not serious efforts to supporting other Graph DBs at this point.

**Comment by magick93** [comment]
Ok, good to hear.

Have you tried any stress tests with OrientDb? I have heard that it has
some performance issues.

And is the plan to be more vendor neutral in terms of graph dbs?

**Comment by Jotschi** [comment]
Hello @magick93 

thank you for your questions.

We started developing Mesh using Neo4j and switched to OrientDB about two years ago. I personally can't confirm most of the criticism that is usually circling around the web concerning OrientDB. We are however only using a certain smaller subset of the OrientDB server features and we are also embedding the graph database. This may avoid some of the issues that other users are facing when using OrientDB. We are for example not executing any OrientDB SQL statements and thus the query parser and query caching mechanism is not used at all.
On the developer side I can only attest that OrientDB's type system (classes) allowed us to directly map our domain model class hierarchically which is pretty neat and indices can be configured in great detail. Writing Tinkerpop code for OrientDB can honestly sometimes be a bit tricky especially when dealing with concurrency this might be easier in Neo4j. There are some parts which could be documented better but you might face similar hurdles when delving into the depths of other graph databases. 

Some time ago I ran performance/load tests in which I imported two million Mesh nodes and OrientDB did not even budge and I did not encountered unexplained performance issues. All the detected issues were related to our Tinkerpop code and quickly fixed.

We occasionally also inspect the memory usage in some larger Gentics Mesh installations ( ~ 400k nodes ). We also have automatic unit tests which assert the performance for certain read/write operations. 
We honestly have currently more issues with Elasticsearch than OrientDB. This is also a reason why we planning to only support an external Elasticsearch instead of embedding it.

On your question about other vendor support:
Yes we want to support other graphdb vendors as well. All the vendor specific graphdb code is contained in one module. So in theory you would just need to implement e.g. a Neo4j module for mesh and utilize it. I initially had modules for Tinkergraph, Neo4j and Stardog but it takes a lot of time to test and verify those modules. I hope that this will be a lot easier once we migrate our code to Tinkerpop 3.x

Could you perhaps explain your OrientDB concerns?
