### ISSUE TITLE
Unable to create list fields of type binary

### ISSUE THREAD

**Issue by vishvish** [gentics/mesh#222]
## Gentics Mesh Version, operating system, or hardware.
- v0.11.2

## Operating System
- MacOS 10.13.1 

## JVM
- Oracle JDK 1.8.0_152

## Problem

Making a new schema: Attempting to create a list field where members are of type binary fails silently in the UI, but backend reports error `java.lang.RuntimeException: Mapping type  for field type {list} unknown.
`
## Reproducer

Create new schema. Add a new field, e.g. 'images' of type 'list' and then choose 'binary' from dropdown. No error in UI, but fails to save silently.

**Comment by Jotschi** [comment]
Binary lists are not implemented. Unfortunately the UI does not reflect this.

I'm not sure whether we'll add support for binary lists. It is in my mind better to create multiple nodes which contain a single binary field and reference those nodes via a binary lists. Otherwise you would not be able to retrieve the binary data via the webroot API.

**Comment by vishvish** [comment]
After some testing, I agree that binary lists are not necessary. Anyway, the minor bug is there in the UI but it's not a serious problem.

**Comment by Jotschi** [comment]
@vishvish We included a fix in 0.11.5 to omit the binary type option for list fields.
