### ISSUE TITLE
Image Resizer Generates Black Images

### ISSUE THREAD

**Issue by Jotschi** [gentics/mesh#240]
In some situations black images are returned by the image resizer.

**Comment by Jotschi** [comment]
Not reproducible. We need more information to debug this.

**Comment by bernhardriegler** [comment]
here is the original image causing issues when resized to width of 250px
https://filebox.apa-it.at/index.php/s/ASLtglh79sz9Giw/download

**Comment by Jotschi** [comment]
Just tested this with corrupt data streams and could not reproduce the error.

**Comment by tpusztaiGentics** [comment]
I also tried to reproduce the issue, without success.
In this particular case (scaling a 7015 x 8751 pixel image down to a width of 250 pixels), the used library (Imgscalr) uses the method `Scalr.scaleImageIncrementally()`, which means that the image is scaled down to the target size over multiple steps. To do the actual scaling, the `Graphics2D.drawImage()` method is used on a `Graphics2D` that has been created from the destination `BufferedImage`. Maybe it's a bug in the `drawImage()` method (which might have already been fixed in a JRE update) or a hardware acceleration issue that only occurs sometimes with a particular hardware configuration.

We also cannot rule out completely a problem with `ImageIO.write()`, but since the resulting black image that Jotschi got from the customer is a valid image, that is probably less likely.

**Comment by Jotschi** [comment]
TODO:
* Update JRE in docker images

**Comment by bernhardriegler** [comment]
URL: https://cyo-mesh-prod.cloud.swarovski.com/api/v1/cyo/nodes/282b3c58fbfd4b6eab3c58fbfd1b6ec8/binary/poster?w=250

**Comment by tpusztaiGentics** [comment]
Unfortunately I did not succeed in reproducing the problem.
I added some [debug code](https://github.com/gentics/mesh/commit/a7640abe3c4e6184f9ce0085e48c2c7bae82cb01) that checks for a black output image after resizing and changes the cache file name for every request. 

I then ran mesh inside an Amazon ECS container and ran test requests using Postman:
1. 300 requests of the form `http://{{host}}:8080/api/v1/demo/webroot/images/Jacket.jpg?w=250`
2. 200 tests of the form `http://{{host}}:8080/api/v1/demo/nodes/{{nodeUUID}}/binary/image?w=250`

The image response was normal every time and also in the binaryImageCache subfolder for this image all the files were of the same size, about 22kb (I created an all black test JPEG of the same output dimensions and that one was about 2kb).

**Comment by Jotschi** [comment]
Closing the issue for now. Lets see whether it reappears and lets revisit this in that case.
