### ISSUE TITLE
Search via graphql (with totalCount) takes much longer than via search-rest-endpoint

### ISSUE THREAD

**Issue by elbird** [gentics/mesh#241]
## Version
0.11.8

## Problem
Search-requests using the same query take longer on the graphql nodes endpoint (with "totalCount"-Parameter activated) than on the project search REST-endpoint.  (for a Request with ~50.000 totalresults via GraphQl ~20s and via Rest-endpoint ~5s) Ideally requests using this endpoints should take roughly the same time.

**Comment by Jotschi** [comment]
The GraphQL query handling implementation makes use of the scroll API. The other implementation directly fetches all results and processes them. Maybe that explains the difference. We could profile this but I think it is not really worth it since we will soon remove the embedded ES from Mesh and that will anyhow affect the overall query performance.
