### ISSUE TITLE
Error in GraphQL query for custom schema

### ISSUE THREAD

**Issue by vishvish** [gentics/mesh#281]
## Gentics Mesh Version, operating system, or hardware.
- v0.16.0

## Operating System
- MacOSX

## JVM
- Oracle JDK 1.8.0_152

## Problem

GraphQL query for nodes based on a custom schema cause an error. The same query for a built-in schema does not. This is when calling the endpoint through code, using the GraphiQL browser, no error occurs.

## Reproducer

The GraphQL query below works
```
{
  schema(name: "content") {
    nodes {
      elements {
        uuid
        fields {
          ... on content {
            title
            content
          }
        }
      }
    }
  }
}
```

I have a custom schema called 'Article' which is almost identical to 'content' and the following GraphQL query (from code) fails:
```
{
  schema(name: "Article") {
    nodes {
      elements {
        uuid
        fields {
          ... on Article {
            title
            synopsis
          }
        }
      }
    }
  }
}
```
The error in the Mesh log is:
```
21:57:08.950 [Chiaroscuro Aipom] WARN  [vert.x-worker-thread-12] - Encountered {1} errors while executing query {{
  schema(name: "Article") {
    nodes {
      elements {
        uuid
        fields {
          ... on Article {
            title
                synopsis
          }
        }
      }
    }
  }
}
}
```
It also does not make any difference whether the schema begins with an uppercase letter or not.

The code and data all appeared to work fine with previous versions, but I cannot easily test without recreating all the data perfectly as the db has been upgraded. I am going to write some test data fixtures in code so I can load and reload them in a deterministic way to Mesh through the API, so I can test against older versions.

**Comment by Jotschi** [comment]
I just created a copy of the content schema on the demo instance and named it "Article". After that I assigned the schema to the project and created a single node in the project using that schema.

The [Example Query](https://demo.getmesh.io/api/v1/demo/graphql/browser/#query=%7B%0A%20%20schema(name%3A%20%22Article%22)%20%7B%0A%20%20%20%20nodes%20%7B%0A%20%20%20%20%20%20elements%20%7B%0A%20%20%20%20%20%20%20%20uuid%0A%20%20%20%20%20%20%20%20fields%20%7B%0A%20%20%20%20%20%20%20%20%20%20...%20on%20Article%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20slug%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A) works for me.

Can you check whether you perhaps did not link the schema to your project? Normally a failed GraphQL request should contain the error information in the response. Did your response yield such info?

**Comment by vishvish** [comment]
Hi @Jotschi, thanks for checking it out. The schema is definitely linked to the demo project (There's only one project). Unfortunately, there's no more information in the mesh log, but I did get this error in the browser console:

`Error: GraphQL error: graphql_error_missing_perm`

But I have no idea what that error means, nor can I find out anything about it by searching. Any idea?

I'm wondering if something has happened internally to the data as I've upgraded Mesh three or four times now. I am going to clear the database and start again.

**Comment by vishvish** [comment]
Further note: without clearing the database, I created a brand-new schema, added a node in said schema, and then ran the query for it. Worked in the graphql client, failed on the server. I am now going to look into whether this is a problem within the javascript client or not.

**Comment by Jotschi** [comment]
@vishvish I might know whats going on. 

Once you log-in mesh via your browser you are authenticated as a user (e.g: admin). And it seems that you access the GraphQL API with a different user on the server-side. This server-side user is lacking the permission to access the schema/node and thus you see the error. The GraphQL query should not fully fail in those cases. Instead only the affected fields should not be listable.
By default Gentics Mesh will utilize the anonymous user to authenticate your requests. This user or to be more exact the role of the user (since roles hold the perms) is lacking the needed permissions.
You can either access the Mesh UI and assign the needed perms to the anonymous role or use a different user to access the API. 

You can access the section via: 

* Admin -> Roles -> anonymous -> Projects
* Admin -> Roles -> anonymous -> Node permissions (Note the tiny drop down on "Read" to apply perms recursively. This is a bit hidden. We are currently re-working the UI to make this workflow easier)
* Admin -> Schemas

It is best to grant read to the project, schemas and the nodes you want to read. You only need to grant permissions to nodes once. If you create additional nodes those nodes will automatically inherit the permissions of their parents.

The whole permission aspect can be a bit complicated. I'll discuss with my team whether we can perhaps incorporate some of those manual steps you did in the new UI.

Let me know whether granting the perms fixes your problems. I'll also add some tests which reflect your situation. The GraphQL error should be easier to understand.

**Comment by vishvish** [comment]
@Jotschi Thanks for the note. I was heading in the direction of roles when I saw the note, and you are right, this is the exact problem, and I did not see that these permissions on the schemas were required. I create these schemas from my own backend software that I'm making and I'll add some more code to handle the permissions once I figure out the API calls that are required.

Thanks for the help and the fixes. You guys do a fabulous job.
