### ISSUE TITLE
List of nodes field doesn't appear in the JSON response if empty

### ISSUE THREAD

**Issue by afilimonov** [gentics/mesh#362]
## Problem

A field with list of nodes type doesn't appear in the JSON response if the list is empty

## Reproducer

1. Create a schema that has 'items' field with list of nodes type
2. Create a node using this schema but don't add any items to the list
3. Retrieve the node using webroot API
4. Items field is not in the response but other fields are.

## Expected behaviour and actual behaviour

Empty items field i.e. "items": []

**Comment by Jotschi** [comment]
@afilimonov 

I think this works as expected. If you create a node without actually storing any data will get back no fields at all. This will apply to node lists and also to string or number fields.

I think the reasoning behind this is to make it easier to utilize a Node Response for an Update Request. This is especially important when handling concurrent update requests.

Lets imagine that null would be returned instead and assuming that we use a schema with three fields (string, nodeList, number). In that case a empty node create response would look like this:

```
…
"fields": {
  "string": null,
  "nodeList": null,
  "number": null
}
…
```

User A will now update the string field using this POST request:

```
…
"fields": {
  "string": "userA_was_here",
  "nodeList": null,
  "number": null
}
…
```

The same time User B wants to update the number:

```
…
"fields": {
  "string": null,
  "nodeList": null,
  "number": 42
}
…
```

Gentics Mesh internally uses null to determine whether a field should be removed. The second request would in turn conflict with the first send request since both requests altered the "string" field.
UserA wanted to update it and UserB did not want to change it but Gentics Mesh can't figure this out. The only way to ignore the "string" field in the second request would be to omit it from the request.

Note: In this fictional situation the request of UserB would fail since Gentics Mesh would detect an unresolvable conflict during the update.

I know this may be not easy to grasp but we intentionally "hide" the fields which have not yet been created. Let me know whether my explanation was helpful. I'll gladly elaborate to help you understand how this mechanism work in more detail (if needed).

**Comment by afilimonov** [comment]
Yes this is helpful. I guess from the API consumer perspective it si a balance between design time discovery ie I know the node has nodeList field which maybe empty and runtime discovery i.e. I work with what is available at  moment.

There a couple of considerations here . Do we differentiate between nodeList: null and nodeList:[]? Are we better off discovering say featured content doing search by ‘featured’ tag? Or should we use a node that has list of featured  content items? With the latter how we handle empty list gracefully on the client side?

**Comment by Jotschi** [comment]
Yes, Gentics Mesh differences between null and [] for field values. Posting `field: null` will result in a deletion of the field. This fails if the field is set to required. Using tags is a good option to find specific set of contents. Handling empty lists on the client side depends on the actual implementation. To make the implementation resilient I suggest to handle null and empty array the same. (Depends of course on your UX requirements). I'm closing the issue. Let me know if you need more feedback.
