### ISSUE TITLE
Question about new plugin system (binary post/pre processors)

### ISSUE THREAD

**Issue by clems159** [gentics/mesh#395]
Hi @Jotschi 

We saw, that you release in 0.19.0 a way to create our own plugins.

Would it be possible for us to create a plugin that modify the behaviour of an existing endpoint.
For example we want to add some post / pre processor in the binary endpoint,
eg validate binary, if image of specified schema type, width / height, re-compress image.

As far as i understand the plugin system, we can create new endpoints but not modify existing ones.

Thanks

**Comment by Jotschi** [comment]
Hi @clems159 , altering the existing API is a bad idea because it would break upcoming tooling / clients for Gentics Mesh. 
We want to add a feature which actually achieves something like you want to do (https://github.com/gentics/mesh/issues/91). However.. you could create your own upload endpoint via a plugin and process the upload there. After that you can redirect the binary stream to the Gentics Mesh upload endpoint. 

We might also allow to hook into certain parts of Gentics Mesh to avoid the REST overhead but this requires considerable planning. Binary processing is certainly a good usecase. I'll add your case to the idea list for enhancements of the plugin system.

**Comment by Jotschi** [comment]
Further progress will be tracked in #91
