### ISSUE TITLE
Breadcrumb Enhancements

### ISSUE THREAD

**Issue by Jotschi** [gentics/mesh#398]
* Reverse the order of the breadcrumb
* Include the basenode in the breadcrumb - https://github.com/gentics/mesh/blob/19f402a82025ae94dacaafe23053378247d70cba/core/src/main/java/com/gentics/mesh/core/data/node/impl/NodeImpl.java#L861

**Comment by rafacm** [comment]
![genticsmesh-breadcrumb-example](https://user-images.githubusercontent.com/340450/39564376-44115040-4eb4-11e8-94ca-f087678b8117.png)

Some thoughts:
> Reverse the order of the breadcrumb
When rendering the component, the crumbs will be rendered from top-level (project) node to the bottom (current) node.

Examples:
1.  WAI-ARIA Authoring Practices for the breadcrumb pattern: https://www.w3.org/TR/wai-aria-practices/#breadcrumb
1.  Breadcrumb Example: https://www.w3.org/TR/wai-aria-practices/examples/breadcrumb/index.html
![aria-practices-breadcrumb](https://user-images.githubusercontent.com/340450/39564297-e7673bc0-4eb3-11e8-8fe6-10d5eb813282.png)

> Include the basenode in the breadcrumb
I would include both the top-level root/project node and the current node

Furthermore:
1. I would make the "breadcrumb" self-contained so that it can be passed to a component and the component can render it without any further REST API requests to Mesh:
  1. Should contain any multi-language information to be rendered in any of the supported languages: https://getmesh.io/docs/beta/features.html#multilanguage

**Comment by Jotschi** [comment]
@rafacm Keep in mind that is also possible to query the breadcrumb via the GraphQL API. This way you are also able to load different languages and more information.

https://goo.gl/Ev7n9K
