### ISSUE TITLE
Microschema Migration

### ISSUE THREAD

**Issue by deckdom** [gentics/mesh#442]
## Gentics Mesh Version, operating system, or hardware.
- v0.19.x

## Problem

After a microschema migration the node which contained that microschema (single microschema field) does not have the field set in the elasticsearch index.
it also doesn't seem to get detected by the `sync`-endpoint which makes it hard to get back into the index again.

**Comment by Jotschi** [comment]
This issue unfortunately revealed a design flaw in the way node index mappings are handled/generated when dealing with micronodes in nodes.

The mapping of an index is created once a schema gets updated.
Updating a microschema will not affect the schema and thus no new index is generated. Unfortunately the documents in the index will be updated in the index. This in turn will cause an error since the new document contains fields which are not listed in the current mapping. Thus the store requests fail and the index is "out dated".

In general elasticsearch index mappings can't be updated. Fields can be added but not changed or removed. We thus can't just update the index.

## Option A - Version the index

We could add versions to the index and manually create a new version of an index if the need arises.
The micronode migration must (maybe as a setup step) determine which node indices need to be re-created. A migration process must be triggered to migrate the data from the old index to the new index.

Estimate: ~7+ PT

## Option B - Remove Strict Mappings for Micronodes

We could revert the previous change which introduced strict mappings for micronodes and thus avoid the situation all together. Downside is that this will break custom mappings for micronodes.

**Comment by Jotschi** [comment]
Related to #777

**Comment by mattbushell** [comment]
On Option B: when and how would custom mappings be created? Presumably at the time of creation one could indicate it should be created with Strict as it is custom, thus leaving the lay developer a good default of non-strict mapping?

Standard to custom migration may be a problem then?

I apologise for the uninformed discussion, im new to both ES and Mesh

**Comment by Jotschi** [comment]
@mattbushell No problem - Mappings for the documents in Elasticsearch are automatically being created by Gentics Mesh. 

Maybe the issue at hand can be also resolved by invoking a migration of the affected nodes. I'll need to check this.

We initially had a solution in which a dynamic (non-strict) mapping was used for micronode fields. This however caused some issues:

* No custom index settings could be defined for micronode fields
* An error would still happen if a field was removed and recreated with a different type. This leads to errors since the dynamic mapping automatically selects the type for the field by the first element that has been inserted. (e.g. first document contains field.micronode.value = 0 ) This would create a number type in the mapping. Changing this to a string will result in an error in ES.

**Comment by mattbushell** [comment]
So Strict mode seems to be to make the mappings read-only effectively. If an existing microschema has a field's type modified how is Strict helping that? Will that not  in turn cause an ES desync with the Mesh microschema as well as the existing node definitions being outdated?

I think i have now exhausted my limited knowledge and leave it to the experts!

**Comment by Jotschi** [comment]
@mattbushell Unfortunately mappings in ES are somewhat read-only. You can add new fields but you can't alter the type of a field without completely re-indexing the data. This is why we migrate the data in Gentics Mesh from the old index to the new index.

I'm sure we will find a solution for the issue.

**Comment by npomaroli** [comment]
Will be fixed with #1266
