### ISSUE TITLE
GraphQL examples break

### ISSUE THREAD

**Issue by joggerjoel** [gentics/mesh#798]
## Gentics Mesh Version, operating system, or hardware.
- v0.36.4

## Operating System
- MacOSX

## JVM
- JSE 1.8.0_152-b16)

## Problem GraphQL examples
https://files.gitter.im/gentics/mesh/D0gU/Screenshot-2019-07-07-at-4.16.02-PM.png
https://files.gitter.im/gentics/mesh/J4aQ/Screenshot-2019-07-07-at-4.26.55-PM.png

Other example that break:
Invoking a search query to find specific nodes,
Loading nodes from a specific schema,
Filter nodes with regular expressions,
Combining different filters

node(uuid: "28f42d43a7604114b42d43a7602114da") {
    path
} works.
Loading ingoing references - works too

**Comment by philippguertler** [comment]
With [0.35.0](https://getmesh.io/docs/changelog/#v0.35.0) we introduced `v2` of the API. In this version fetching fields in GraphQL works differently. See https://github.com/gentics/mesh/issues/428 for more details.

You can choose to use `/api/v1` instead or use the new query syntax. We recommend using the new syntax since `v1` is deprecated and will be removed in the future. 

The examples on our website still use `v1`. Thanks for pointing that out. We will fix that.
