### ISSUE TITLE
Don't use Thread.sleep for OConcurrentModificationException retries

### ISSUE THREAD

**Issue by mephinet** [gentics/mesh#825]
Currently, Mesh uses `Thread.sleep` to retry when transactions fail with `OConcurrentModificationException` or equivalent (cf. https://github.com/gentics/mesh/blob/0.36.6/databases/orientdb/src/main/java/com/gentics/mesh/graphdb/OrientDBDatabase.java#L306)

This results in sub-optimal behavior, as the whole thread is blocked, which is logged as `Thread ... has been blocked for ... ms, time limit is 2000 ms`. IMHO it would improve performance to schedule a handler for later execution (e.g. with `vertx.setTimer`) instead of sleeping. Furthermore, the max random delay should be a lot smaller (like 100ms instead of 6s)...

Mesh v0.36.6 on Linux

**Comment by Jotschi** [comment]
We can't use async code at this place since the transaction / graph code is actually blocking. The used Thread sleep variant is also the same solution that Tinkerpop uses when retrying a transaction. The issue at hand is however that the max execution time exceeds the accumulated transaction time.

Afaik reducing the delay caused congestion and even more errors. I however think that we should make this configurable and try to reduce this in order to boost write performance.

**Comment by Jotschi** [comment]
Default values changed in 0.40.0
